[train]
max_tokens_per_batch = 25000
label_smoothing = 0.1
max_epochs = 20

[train.optim]
name = "adam"
lr = 0.0005
betas = [0.9, 0.98]
eps = 1e-9

[train.model]
d_model = 1024
num_heads = 16
num_layers = 6
dim_feedforward = 4096
dropout = 0.3

[train.lr_scheduler]
type = 'inverse_sqrt'
warmup_steps = 4000
warmup_decay = 0.01
